name: flutter_map_redux
description: Prueba de redux
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State management dependecies
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  flutter_hooks: ^0.18.5+1
  redux_thunk: ^0.4.0
  http: ^0.13.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true